### ISSUE TITLE
update doesn't work?

### ISSUE THREAD

**Issue by mellerbeck** [TotallyInformation/alternate-node-red-installer#7]
I run

npm run check-master
With this response
`> node-red-master@2.0.3 check-master C:\Nodered`
`> npm outdated`

`Package   Current  Wanted  Latest  Location`
`node-red    2.0.6   2.1.3   2.1.3  node-red-master`

Then run
>npm run update-master

`> node-red-master@2.0.3 update-master C:\Nodered`
`> npm install --production --unsafe-perm`

`npm WARN node-red-master@2.0.3 No repository field.`

`audited 290 packages in 1.528s`

`27 packages are looking for funding`
 ` run `npm fund` for details`

`found 0 vulnerabilities`

But doesn't look like it actually does anything?

**Comment by TotallyInformation** [comment]
The package.json file(s) need updating in order to fetch a newer major version. This package is not automatically updated in line with Node-RED or other major versions.

**Comment by TotallyInformation** [comment]
Corrected for v4 which is about to be published. The new version will ALWAYS install the latest version.

If you wanted the previous version of the script to work, assuming that you have run it at least once before, it will have changed the version spec from `"*"` to something like `"~2.0.1"`. So to get a newer major version you would need to change that spec. You also need to understand the difference between the folder where node-red is installed and the `data` sub-folder. Each has a package.json file so compare them to see how they work.

The npm scripts defined in the 2 package.json files are for convenience, they do not cover all possible requirements.

**Comment by mellerbeck** [comment]
Nice! Thanks for my favorite way to run nodered!
